// Duplicate an existing ActiveCampaign deal onto a (test) email.
// Used in the booking-management hero to quickly clone a real deal and run
// tests against the copy without touching the original.
//
// Some data cannot be strictly duplicated and is reset on the copy:
//  - the AC deal id (auto-generated by AC)
//  - the booked_date / booked_id link (lives in Supabase, not recreated here)
//  - linkBms / paiementLink (point to the original booked date)
//  - conversionDate (a fresh deal has not converted yet)
// Payment amounts (alreadyPaid / restToPay) ARE carried over so the copy can be
// used to test flows that depend on them.

// Custom fields that AC stores as multi-value (must be sent as arrays).
const ARRAY_FIELDS = new Set(['insurance', 'indivRoom'])

// Custom fields typed as numbers (mirror the funnel payload shape).
const NUMERIC_FIELDS = new Set([
  'nbTravelers', 'nbAdults', 'nbChildren', 'insuranceCommissionPrice', 'marginPerTraveler',
  'totalMargin', 'flightMargin', 'pricePerTraveler', 'restTravelersToPay', 'alreadyPaid', 'restToPay',
  'insuranceCommissionPerTraveler', 'depositPrice', 'basePricePerTraveler', 'zoneChapka',
  'indivRoomPrice', 'promoValue', 'restToPayPerTraveler', 'totalTravelPrice', 'flightPrice',
  'extensionPrice', 'promoChildren', 'maxChildrenAge', 'promoTeen', 'maxTeenAge', 'nbUnderAge',
  'nbTeen', 'promoEarlybird', 'promoLastMinute', 'agentCost', 'extraMarginPerTraveler',
])

// Fields that must not be carried over to the copy.
const STRIPPED_FIELDS = new Set([
  'linkBms', 'paiementLink', 'conversionDate',
])

export default defineEventHandler(async (event) => {
  const dealId = parseInt(event.context.params.dealId)
  if (!Number.isInteger(dealId)) {
    throw createError({ statusCode: 400, statusMessage: 'Deal ID should be an integer' })
  }

  const body = await readBody(event)
  const email = body?.email?.trim()
  if (!email || !/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)) {
    throw createError({ statusCode: 400, statusMessage: 'Un email valide est requis' })
  }

  try {
    const [{ deal }, customFields] = await Promise.all([
      activecampaign.getDealById(dealId),
      activecampaign.getDealCustomFields(dealId),
    ])

    if (!deal) {
      throw createError({ statusCode: 404, statusMessage: 'Deal source introuvable' })
    }

    // Rebuild a flat deal payload from the source custom fields, mirroring the
    // shape the funnel sends (arrays / numbers) so AC accepts every field.
    const fields = {}
    for (const [key, rawValue] of Object.entries(customFields)) {
      if (STRIPPED_FIELDS.has(key) || rawValue === null || rawValue === undefined) continue
      if (ARRAY_FIELDS.has(key)) {
        fields[key] = Array.isArray(rawValue) ? rawValue : [rawValue]
      }
      else if (NUMERIC_FIELDS.has(key)) {
        fields[key] = Number(rawValue) || 0
      }
      else {
        fields[key] = rawValue
      }
    }

    const payload = {
      ...fields,
      currency: deal.currency || 'eur',
      group: String(deal.group),
      owner: String(deal.owner),
      stage: String(deal.stage),
      title: `[TEST] ${deal.title || 'Deal'}`,
      value: Number(deal.value) || 0,
      currentStep: 'Deal dupliqué (test)',
      // Contact = the provided test email.
      email,
      ...(body.firstname && { firstname: body.firstname.trim() }),
      ...(body.lastname && { lastname: body.lastname.trim() }),
      ...(body.phone && { phone: String(body.phone).trim() }),
    }

    const newDealId = await activecampaign.createDeal(payload)
    return { dealId: newDealId }
  }
  catch (err) {
    if (err?.statusCode) throw err
    console.error('Error duplicating deal', dealId, err)
    throw createError({ statusCode: 500, statusMessage: 'Erreur lors de la duplication du deal' })
  }
})
