-- ============================================================================
-- RUN ON: DASHBOARD Supabase project (new project)
-- Purpose: create mirror tables matching prod schema 1:1.
-- Logical replication requires identical schema + column types between
-- publisher and subscriber. These tables sit in `public` (same as prod).
-- They are populated by the subscription (see 04_subscription.sql) and must
-- be treated as read-only on this side.
-- ============================================================================

CREATE TABLE IF NOT EXISTS "public"."activecampaign_clients" (
    "id"               bigint                   NOT NULL,
    "created_at"       timestamp with time zone NOT NULL DEFAULT now(),
    "firstname"        character varying,
    "lastname"         character varying,
    "email"            character varying        NOT NULL,
    "birthdate"        timestamp without time zone,
    "contact"          bigint                   NOT NULL,
    "zip_code"         bigint,
    "city"             character varying,
    "phone"            text,
    "iso_contact"      text,
    "tags"             text[],
    "address"          text,
    "mdate"            timestamp with time zone,
    "updated_at"       timestamp with time zone,
    "optin_newsletter" boolean,
    CONSTRAINT "activecampaign_clients_pkey" PRIMARY KEY ("id", "email"),
    CONSTRAINT "activecampaign_clients_duplicate_contact_key" UNIQUE ("contact")
);

CREATE TABLE IF NOT EXISTS "public"."activecampaign_deals" (
    "id"                              bigint                   NOT NULL,
    "created_at"                      timestamp with time zone NOT NULL DEFAULT now(),
    "contact"                         bigint                   NOT NULL,
    "title"                           character varying,
    "status"                          character varying,
    "stage"                           character varying,
    "total_value"                     numeric,
    "price_per_traveler"              numeric,
    "nb_traveler"                     numeric,
    "nb_adults"                       numeric,
    "nb_children"                     numeric,
    "travel_type"                     character varying,
    "indiv_room"                      boolean,
    "rest_to_pay"                     numeric,
    "total_paid"                      numeric,
    "margin_per_traveler"             numeric,
    "flight_margin"                   numeric,
    "total_margin"                    numeric,
    "insurance_commission"            numeric,
    "insurance_choice"                character varying,
    "pipeline_id"                     smallint,
    "promo_code"                      character varying,
    "insurance_price_per_traveler"    numeric,
    "country"                         character varying,
    "is_couple"                       boolean,
    "lost_reason"                     character varying,
    "applied_promo_per_traveler"      numeric,
    "children_promo"                  numeric,
    "teen_promo"                      numeric,
    "rest_to_pay_per_traveler"        numeric,
    "iso"                             character varying,
    "max_teen_age"                    smallint,
    "max_children_age"                smallint,
    "flight_ticket_price_per_traveler" numeric,
    "departure_date"                  timestamp without time zone,
    "return_date"                     timestamp without time zone,
    "conversion_date"                 timestamp without time zone,
    "seller"                          character varying,
    "source"                          character varying,
    "paiement_method"                 character varying,
    "updated_at"                      timestamp with time zone,
    "mdate"                           timestamp with time zone,
    "slug"                            text,
    "current_step"                    text,
    "utm"                             text,
    "acquisition_source"              text,
    "other_acquisition_source"        text,
    "extension_price"                 numeric,
    "indiv_room_price"                numeric,
    "deposit_price"                   numeric,
    "agent_cost"                      numeric,
    "promo_earlybird"                 numeric,
    "got_earlybird"                   boolean,
    "promo_last_minute"               numeric,
    "got_last_minute"                 boolean,
    "nb_teen"                         numeric,
    "nb_under_age"                    numeric,
    "forecasted_closing_date"         timestamp without time zone,
    "is_cap_exploraction"             boolean,
    "flight_ticket_bought"            boolean,
    "zone_chapka"                     numeric,
    "link_bms"                        text,
    "include_flight"                  boolean,
    "currency"                        text,
    "owner_id"                        text,
    "stage_id"                        text,
    "win_probability"                 smallint,
    "next_date"                       timestamp with time zone,
    "next_task_id"                    text,
    CONSTRAINT "activecampaign_deals_pkey" PRIMARY KEY ("id", "contact")
);

CREATE TABLE IF NOT EXISTS "public"."travel_dates" (
    "id"                         uuid                     NOT NULL DEFAULT gen_random_uuid(),
    "created_at"                 timestamp with time zone NOT NULL DEFAULT now(),
    "published"                  boolean DEFAULT false,
    "travel_slug"                character varying,
    "departure_date"             date,
    "return_date"                date,
    "max_travelers"              integer,
    "min_travelers"              integer,
    "booked_seat"                integer,
    "include_flight"             boolean DEFAULT false,
    "flight_price"               numeric DEFAULT 0,
    "badges"                     text,
    "starting_price"             numeric DEFAULT 0,
    "early_bird"                 boolean DEFAULT true,
    "last_minute"                boolean DEFAULT false,
    "is_custom_travel"           boolean DEFAULT false,
    "custom_display"             boolean DEFAULT false,
    "displayed_min_travelers"    integer,
    "displayed_max_travelers"    integer,
    "displayed_booked_seat"      integer,
    "displayed_include_flight"   boolean DEFAULT false,
    "displayed_badges"           text,
    "displayed_starting_price"   numeric,
    "displayed_last_minute"      boolean DEFAULT false,
    "displayed_early_bird"       boolean DEFAULT false,
    "status"                     text,
    "is_indiv_travel"            boolean DEFAULT false,
    "deleted"                    boolean NOT NULL DEFAULT false,
    "is_test"                    boolean NOT NULL DEFAULT false,
    "closing_days"               bigint,
    "displayed_status"           text,
    "updated_at"                 timestamp with time zone,
    "last_editor"                text,
    "departure_id"               text,
    "bms_reference"              text,
    "travel_type_prefix"         text,
    "co_filling"                 integer DEFAULT 0,
    CONSTRAINT "travel_dates_pkey" PRIMARY KEY ("id"),
    CONSTRAINT "travel_dates_departure_id_key" UNIQUE ("departure_id")
);

CREATE TABLE IF NOT EXISTS "public"."booked_dates" (
    "id"               uuid                     NOT NULL DEFAULT gen_random_uuid(),
    "created_at"       timestamp with time zone NOT NULL DEFAULT now(),
    "deal_id"          bigint                   NOT NULL,
    "booked_places"    bigint                   DEFAULT 0,
    "is_option"        boolean                  DEFAULT false,
    "expiracy_date"    date,
    "travel_date_id"   uuid,
    "is_test"          boolean                  DEFAULT false,
    "deleted"          boolean                  NOT NULL DEFAULT false,
    "transaction_id"   text,
    "payment_type"     text,
    CONSTRAINT "booked_dates_pkey" PRIMARY KEY ("id", "deal_id"),
    CONSTRAINT "booked_dates_deal_id_key" UNIQUE ("deal_id")
);

ALTER TABLE "public"."activecampaign_deals"   REPLICA IDENTITY FULL;
ALTER TABLE "public"."activecampaign_clients" REPLICA IDENTITY FULL;
ALTER TABLE "public"."travel_dates"           REPLICA IDENTITY FULL;
ALTER TABLE "public"."booked_dates"           REPLICA IDENTITY FULL;
