import {defineField, defineType} from 'sanity'

export const voyageType = defineType({
  name: 'voyage',
  title: 'Voyage',
  type: 'document',
  groups: [
    {name: 'basic', title: 'Informations de Base'},
    {name: 'content', title: 'Contenu'},
    {name: 'programme', title: 'Programme'},
    {name: 'pricing', title: 'Tarifs'},
    {name: 'housing', title: 'Hébergement'},
    {name: 'media', title: 'Médias'},
    {name: 'faq', title: 'FAQ'},
    {name: 'seo', title: 'SEO'},
  ],
  fields: [
    defineField({name: 'published', type: 'boolean', group: 'basic'}),
    defineField({name: 'title', type: 'string', validation: (r) => r.required(), group: 'basic'}),
    defineField({name: 'slug', type: 'slug', options: {source: 'title'}, validation: (r) => r.required(), group: 'basic'}),
    defineField({
      name: 'destinations',
      title: 'Destinations',
      type: 'array',
      of: [{type: 'reference', to: [{type: 'destination'}]}],
      validation: (r) => r.min(1),
      group: 'basic'
    }),
    defineField({name: 'groupeAvailable', type: 'boolean', group: 'basic'}),
    defineField({name: 'privatisationAvailable', type: 'boolean', group: 'basic'}),
    defineField({name: 'customAvailable', type: 'boolean', group: 'basic'}),
    defineField({
      name: 'experienceType',
      title: 'Experience',
      type: 'reference',
      to: [{type: 'experience'}],
      group: 'basic'
    }),
    defineField({name: 'level', type: 'string', group: 'basic'}),
    defineField({
      name: 'categories',
      type: 'array',
      of: [{type: 'reference', to: [{type: 'category'}]}],
      group: 'basic'
    }),
    defineField({name: 'duration', type: 'number', group: 'basic'}),
    defineField({name: 'nights', type: 'number', group: 'basic'}),
    defineField({name: 'includeFlight', type: 'boolean', group: 'basic'}),
    defineField({name: 'housingType', type: 'string', group: 'basic'}),
    defineField({
      name: 'idealPeriods',
      type: 'object',
      group: 'basic',
      fields: [
        {name: 'toutePeriodes', type: 'boolean'} as any,
        {name: 'janvier', type: 'boolean'} as any,
        {name: 'fevrier', type: 'boolean'} as any,
        {name: 'mars', type: 'boolean'} as any,
        {name: 'avril', type: 'boolean'} as any,
        {name: 'mai', type: 'boolean'} as any,
        {name: 'juin', type: 'boolean'} as any,
        {name: 'juillet', type: 'boolean'} as any,
        {name: 'aout', type: 'boolean'} as any,
        {name: 'septembre', type: 'boolean'} as any,
        {name: 'octobre', type: 'boolean'} as any,
        {name: 'novembre', type: 'boolean'} as any,
        {name: 'decembre', type: 'boolean'} as any,
      ],
    }),
    defineField({
      name: 'monthlyAvailability',
      type: 'object',
      group: 'basic',
      fields: [
        {name: 'toutePeriodes', type: 'boolean'} as any,
        {name: 'janvier', type: 'boolean'} as any,
        {name: 'fevrier', type: 'boolean'} as any,
        {name: 'mars', type: 'boolean'} as any,
        {name: 'avril', type: 'boolean'} as any,
        {name: 'mai', type: 'boolean'} as any,
        {name: 'juin', type: 'boolean'} as any,
        {name: 'juillet', type: 'boolean'} as any,
        {name: 'aout', type: 'boolean'} as any,
        {name: 'septembre', type: 'boolean'} as any,
        {name: 'octobre', type: 'boolean'} as any,
        {name: 'novembre', type: 'boolean'} as any,
        {name: 'decembre', type: 'boolean'} as any,
      ],
    }),
    defineField({name: 'minAge', type: 'number', initialValue: 8, group: 'basic'}),
    defineField({name: 'rating', type: 'number', group: 'basic'}),
    defineField({name: 'comments', type: 'number', group: 'basic'}),
    defineField({name: 'miniatureDisplay', type: 'string', group: 'basic'}),
    defineField({
      name: 'authorNote',
      type: 'object',
      group: 'content',
      fields: [
        {name: 'text', type: 'text'},
        {name: 'author', type: 'reference', to: [{type: 'teamMember'}]},
        {name: 'affixeAuthor', type: 'string'},
      ],
    }),
    defineField({
      name: 'experiencesBlock',
      type: 'array',
      of: [{type: 'string'}],
      group: 'content'
    }),
    defineField({name: 'description', type: 'text', group: 'content'}),
    defineField({name: 'emailDescription', type: 'text', group: 'content'}),
    defineField({name: 'metaDescription', type: 'text', group: 'content'}),
    defineField({
      name: 'badgeSection',
      type: 'object',
      group: 'content',
      fields: [
        {name: 'groupeBadge', type: 'object', fields: [
          {name: 'text', type: 'string'} as any,
          {name: 'visible', type: 'boolean'} as any,
        ]} as any,
        {name: 'durationBadge', type: 'object', fields: [
          {name: 'text', type: 'string'} as any,
          {name: 'visible', type: 'boolean'} as any,
        ]} as any,
        {name: 'includeFlightBadge', type: 'object', fields: [
          {name: 'text', type: 'string'} as any,
          {name: 'visible', type: 'boolean'} as any,
        ]} as any,
        {name: 'housingBadge', type: 'object', fields: [
          {name: 'text', type: 'string'} as any,
          {name: 'visible', type: 'boolean'} as any,
        ]} as any,
        {name: 'periodBadge', type: 'object', fields: [
          {name: 'text', type: 'string'} as any,
          {name: 'visible', type: 'boolean'} as any,
        ]} as any,
      ],
    }),
    defineField({
      name: 'programmeBlock',
      type: 'array',
      group: 'programme',
      of: [{
        type: 'object',
        fields: [
          {name: 'title', type: 'string'} as any,
          {name: 'badgeText', type: 'string'} as any,
          {name: 'description', type: 'text'} as any,
          {name: 'photo', type: 'image', options: {hotspot: true}} as any,
          {name: 'denivellation', type: 'string'} as any,
          {name: 'road', type: 'string'} as any,
          {name: 'night', type: 'string'} as any,
        ],
      }],
    }),
    defineField({
      name: 'pricingDetailsBlock',
      type: 'object',
      group: 'pricing',
      fields: [
        {name: 'include', type: 'array', of: [{type: 'string'}]} as any,
        {name: 'exclude', type: 'array', of: [{type: 'string'}]} as any,
      ],
    }),
    defineField({
      name: 'pricing',
      type: 'object',
      group: 'pricing',
      fields: [
        {name: 'startingPrice', type: 'number'} as any,
        {name: 'lastMinuteAvailable', type: 'boolean'} as any,
        {name: 'lastMinuteReduction', type: 'number'} as any,
        {name: 'earlyBirdAvailable', type: 'boolean'} as any,
        {name: 'earlyBirdReduction', type: 'number'} as any,
        {name: 'maxTravelers', type: 'number'} as any,
        {name: 'minTravelersToConfirm', type: 'number'} as any,
        {name: 'indivRoom', type: 'boolean'} as any,
        {name: 'forcedIndivRoom', type: 'boolean'} as any,
        {name: 'indivRoomPrice', type: 'number'} as any,
        {name: 'cseReduction', type: 'number'} as any,
        {name: 'cseAvailable', type: 'boolean'} as any,
        {name: 'childrenPromo', type: 'number'} as any,
        {name: 'childrenAge', type: 'number', initialValue: 12} as any,
        {name: 'airportCode', type: 'array', of: [{type: 'string'}]} as any,
      ],
    }),
    defineField({name: 'accompanistsDescription', type: 'string', group: 'housing'}),
    defineField({
      name: 'accompanistsList',
      type: 'array',
      group: 'housing',
      of: [{
        type: 'object',
        fields: [
          {name: 'name', type: 'string'} as any,
          {name: 'description', type: 'text'} as any,
          {name: 'role', type: 'string'} as any,
          {name: 'image', type: 'image', options: {hotspot: true}} as any,
        ],
      }],
    }),
    defineField({
      name: 'housingBlock',
      type: 'array',
      group: 'housing',
      of: [{
        type: 'object',
        fields: [
          {name: 'title', type: 'string'} as any,
          {name: 'housingType', type: 'string'} as any,
          {name: 'housingMood', type: 'string'} as any,
          {name: 'image', type: 'array', of: [{type: 'image', options: {hotspot: true}, fields: [{name: 'alt', type: 'string'} as any]}]} as any,
        ],
      }],
    }),
    defineField({
      name: 'image',
      type: 'image',
      options: {hotspot: true},
      group: 'media',
      fields: [{name: 'alt', type: 'string'} as any],
    }),
    defineField({
      name: 'imageSecondary',
      type: 'image',
      options: {hotspot: true},
      group: 'media',
      fields: [{name: 'alt', type: 'string'} as any],
    }),
    defineField({
      name: 'photosList',
      type: 'array',
      group: 'media',
      of: [{type: 'image', options: {hotspot: true}, fields: [{name: 'alt', type: 'string'} as any]}],
    }),
    defineField({name: 'videoLinks', type: 'array', of: [{type: 'url'}], group: 'media'}),
    defineField({
      name: 'faqBlock',
      type: 'object',
      group: 'faq',
      fields: [
        {name: 'faqList', type: 'array', of: [{
          type: 'object',
          fields: [
            {name: 'question', type: 'string'} as any,
            {name: 'answer', type: 'text'} as any,
          ],
        }]} as any,
      ],
    }),
    defineField({
      name: 'seoSection',
      type: 'object',
      group: 'seo',
      fields: [
        {name: 'metaTitle', type: 'string'} as any,
        {name: 'canonicalUrl', type: 'url'} as any,
        {name: 'ogTitle', type: 'string'} as any,
        {name: 'ogDescription', type: 'text'} as any,
        {name: 'ogImage', type: 'image', options: {hotspot: true}, fields: [{name: 'alt', type: 'string'} as any]} as any,
        {name: 'twitterTitle', type: 'string'} as any,
        {name: 'twitterDescription', type: 'text'} as any,
        {name: 'twitterImage', type: 'image', options: {hotspot: true}, fields: [{name: 'alt', type: 'string'} as any]} as any,
        {name: 'twitterCard', type: 'string'} as any,
      ],
    }),
  ],
})

