import {defineField, defineType} from 'sanity'

export const voyageType = defineType({
  name: 'voyage',
  title: 'Voyage',
  type: 'document',
  fields: [
    defineField({name: 'published', type: 'boolean'}),
    defineField({name: 'title', type: 'string', validation: (r) => r.required()}),
    defineField({name: 'slug', type: 'slug', options: {source: 'title'}, validation: (r) => r.required()}),
    defineField({
      name: 'destinations',
      title: 'Destinations',
      type: 'array',
      of: [{type: 'reference', to: [{type: 'destination'}]}],
      validation: (r) => r.min(1),
    }),
    defineField({name: 'groupeAvailable', type: 'boolean'}),
    defineField({name: 'privatisationAvailable', type: 'boolean'}),
    defineField({name: 'customAvailable', type: 'boolean'}),
    defineField({
      name: 'experienceType',
      title: 'Experience',
      type: 'reference',
      to: [{type: 'experience'}],
    }),
    defineField({name: 'level', type: 'string'}),
    defineField({
      name: 'categories',
      type: 'array',
      of: [{type: 'reference', to: [{type: 'category'}]}],
    }),
    defineField({name: 'duration', type: 'number'}),
    defineField({name: 'nights', type: 'number'}),
    defineField({name: 'includeFlight', type: 'boolean'}),
    defineField({name: 'housingType', type: 'string'}),
    defineField({
      name: 'idealPeriods',
      type: 'object',
      fields: [
        {name: 'toutePeriodes', type: 'boolean'} as any,
        {name: 'janvier', type: 'boolean'} as any,
        {name: 'fevrier', type: 'boolean'} as any,
        {name: 'mars', type: 'boolean'} as any,
        {name: 'avril', type: 'boolean'} as any,
        {name: 'mai', type: 'boolean'} as any,
        {name: 'juin', type: 'boolean'} as any,
        {name: 'juillet', type: 'boolean'} as any,
        {name: 'aout', type: 'boolean'} as any,
        {name: 'septembre', type: 'boolean'} as any,
        {name: 'octobre', type: 'boolean'} as any,
        {name: 'novembre', type: 'boolean'} as any,
        {name: 'decembre', type: 'boolean'} as any,
      ],
    }),
    defineField({
      name: 'monthlyAvailability',
      type: 'object',
      fields: [
        {name: 'toutePeriodes', type: 'boolean'} as any,
        {name: 'janvier', type: 'boolean'} as any,
        {name: 'fevrier', type: 'boolean'} as any,
        {name: 'mars', type: 'boolean'} as any,
        {name: 'avril', type: 'boolean'} as any,
        {name: 'mai', type: 'boolean'} as any,
        {name: 'juin', type: 'boolean'} as any,
        {name: 'juillet', type: 'boolean'} as any,
        {name: 'aout', type: 'boolean'} as any,
        {name: 'septembre', type: 'boolean'} as any,
        {name: 'octobre', type: 'boolean'} as any,
        {name: 'novembre', type: 'boolean'} as any,
        {name: 'decembre', type: 'boolean'} as any,
      ],
    }),
    defineField({name: 'minAge', type: 'number', initialValue: 8}),
    defineField({name: 'rating', type: 'number'}),
    defineField({name: 'comments', type: 'number'}),
    defineField({name: 'miniatureDisplay', type: 'string'}),
    defineField({
      name: 'authorNote',
      type: 'object',
      fields: [
        {name: 'text', type: 'array', of: [{type: 'block'}]} as any,
        {name: 'author', type: 'reference', to: [{type: 'teamMember'}]} as any,
        {name: 'affixeAuthor', type: 'string'} as any,
      ],
    }),
    defineField({
      name: 'experiencesBlock',
      type: 'array',
      of: [{type: 'string'}],
    }),
    defineField({name: 'description', type: 'array', of: [{type: 'block'}]}),
    defineField({name: 'emailDescription', type: 'text'}),
    defineField({name: 'metaDescription', type: 'text'}),
    defineField({
      name: 'badgeSection',
      type: 'object',
      fields: [
        {name: 'groupeBadge', type: 'object', fields: [
          {name: 'text', type: 'string'} as any,
          {name: 'visible', type: 'boolean'} as any,
        ]} as any,
        {name: 'durationBadge', type: 'object', fields: [
          {name: 'text', type: 'string'} as any,
          {name: 'visible', type: 'boolean'} as any,
        ]} as any,
        {name: 'includeFlightBadge', type: 'object', fields: [
          {name: 'text', type: 'string'} as any,
          {name: 'visible', type: 'boolean'} as any,
        ]} as any,
        {name: 'housingBadge', type: 'object', fields: [
          {name: 'text', type: 'string'} as any,
          {name: 'visible', type: 'boolean'} as any,
        ]} as any,
        {name: 'periodBadge', type: 'object', fields: [
          {name: 'text', type: 'string'} as any,
          {name: 'visible', type: 'boolean'} as any,
        ]} as any,
      ],
    }),
    defineField({
      name: 'programmeBlock',
      type: 'array',
      of: [{
        type: 'object',
        fields: [
          {name: 'title', type: 'string'} as any,
          {name: 'badgeText', type: 'string'} as any,
          {name: 'description', type: 'array', of: [{type: 'block'}]} as any,
          {name: 'photo', type: 'image', options: {hotspot: true}} as any,
          {name: 'denivellation', type: 'string'} as any,
          {name: 'road', type: 'string'} as any,
          {name: 'night', type: 'string'} as any,
        ],
      }],
    }),
    defineField({
      name: 'pricingDetailsBlock',
      type: 'object',
      fields: [
        {name: 'include', type: 'array', of: [{type: 'string'}]} as any,
        {name: 'exclude', type: 'array', of: [{type: 'string'}]} as any,
      ],
    }),
    defineField({
      name: 'pricing',
      type: 'object',
      fields: [
        {name: 'startingPrice', type: 'number'} as any,
        {name: 'lastMinuteAvailable', type: 'boolean'} as any,
        {name: 'lastMinuteReduction', type: 'number'} as any,
        {name: 'earlyBirdAvailable', type: 'boolean'} as any,
        {name: 'earlyBirdReduction', type: 'number'} as any,
        {name: 'maxTravelers', type: 'number'} as any,
        {name: 'minTravelersToConfirm', type: 'number'} as any,
        {name: 'indivRoom', type: 'boolean'} as any,
        {name: 'forcedIndivRoom', type: 'boolean'} as any,
        {name: 'indivRoomPrice', type: 'number'} as any,
        {name: 'cseReduction', type: 'number'} as any,
        {name: 'cseAvailable', type: 'boolean'} as any,
        {name: 'childrenPromo', type: 'number'} as any,
        {name: 'childrenAge', type: 'number', initialValue: 12} as any,
        {name: 'airportCode', type: 'array', of: [{type: 'string'}]} as any,
      ],
    }),
    defineField({name: 'accompanistsDescription', type: 'string'}),
    defineField({
      name: 'accompanistsList',
      type: 'array',
      of: [{
        type: 'object',
        fields: [
          {name: 'name', type: 'string'} as any,
          {name: 'description', type: 'array', of: [{type: 'block'}]} as any,
          {name: 'role', type: 'string'} as any,
          {name: 'image', type: 'image', options: {hotspot: true}} as any,
        ],
      }],
    }),
    defineField({
      name: 'housingBlock',
      type: 'array',
      of: [{
        type: 'object',
        fields: [
          {name: 'title', type: 'string'} as any,
          {name: 'housingType', type: 'string'} as any,
          {name: 'housingMood', type: 'string'} as any,
          {name: 'image', type: 'array', of: [{
            type: 'object',
            fields: [
              {name: 'src', type: 'image', options: {hotspot: true}} as any,
              {name: 'alt', type: 'string'} as any,
            ],
          }]} as any,
        ],
      }],
    }),
    defineField({
      name: 'image',
      type: 'image',
      options: {hotspot: true},
      fields: [{name: 'alt', type: 'string'} as any],
    }),
    defineField({
      name: 'imageSecondary',
      type: 'image',
      options: {hotspot: true},
      fields: [{name: 'alt', type: 'string'} as any],
    }),
    defineField({
      name: 'photosList',
      type: 'array',
      of: [{type: 'image', options: {hotspot: true}}],
    }),
    defineField({name: 'videoLinks', type: 'array', of: [{type: 'url'}]}),
    defineField({
      name: 'faqBlock',
      type: 'object',
      fields: [
        {name: 'faqList', type: 'array', of: [{
          type: 'object',
          fields: [
            {name: 'question', type: 'string'} as any,
            {name: 'answer', type: 'array', of: [{type: 'block'}]} as any,
          ],
        }]} as any,
      ],
    }),
    defineField({
      name: 'seoSection',
      type: 'object',
      fields: [
        {name: 'metaTitle', type: 'string'} as any,
        {name: 'canonicalUrl', type: 'url'} as any,
        {name: 'ogTitle', type: 'string'} as any,
        {name: 'ogDescription', type: 'array', of: [{type: 'block'}]} as any,
        {name: 'ogImage', type: 'image', options: {hotspot: true}, fields: [{name: 'alt', type: 'string'} as any]} as any,
        {name: 'twitterTitle', type: 'string'} as any,
        {name: 'twitterDescription', type: 'array', of: [{type: 'block'}]} as any,
        {name: 'twitterImage', type: 'image', options: {hotspot: true}, fields: [{name: 'alt', type: 'string'} as any]} as any,
        {name: 'twitterCard', type: 'string'} as any,
      ],
    }),
  ],
})

