<template>
  <v-container>
    <v-row>
      <v-col
        cols="6"
      >
        <v-img
          :src="props.images[0]"
          height="100%"
          cover
        />
      </v-col>
      <v-col
        cols="6"
      >
        <v-row>
          <v-col
            cols="12"
          >
            <v-img
              :src="props.images[1]"
              height="100%"
              cover
            />
          </v-col>
          <v-col
            cols="6"
          >
            <v-img
              :src="props.images[2]"
              height="100%"
              cover
            />
          </v-col>
          <v-col cols="6">
            <v-img
              :src="props.images[3]"
              height="100%"
              cover
            />
          </v-col>
        </v-row>
      </v-col>
    </v-row>
    <v-row>
      <v-col
        cols="6"
      >
        <v-row>
          <v-col
            cols="12"
          >
            <v-img
              :src="props.images[0]"
              height="100%"
              cover
            />
          </v-col>
          <v-col
            cols="6"
          >
            <v-img
              :src="props.images[1]"
              height="100%"
              cover
            />
          </v-col>
          <v-col
            cols="6"
          >
            <v-img
              :src="props.images[2]"
              height="100%"
              cover
            />
          </v-col>
        </v-row>
      </v-col>
      <v-col
        cols="6"
      >
        <v-img
          :src="props.images[3]"
          height="100%"
          cover
        />
      </v-col>
    </v-row>
  </v-container>
</template>

<script setup>
const props = defineProps({
  images: {
    type: Array,
  },
})
</script>
